title: My site
description: Personal Jekyll blog on GitHub Pages
theme: jekyll-theme-hacker

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc
